title: C-SET Lab
description: Center for Systems Epidemiology and Transplant Exposomics

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  - research.md
  - infrastructure.md
  - team.md
